
import 'bootstrap/dist/css/bootstrap.min.css';
import '../styles/global.css';

import 'react-toastify/dist/ReactToastify.css';
import ModalProvider from '@/components/modalProvider';
import { ToastContainer, Zoom } from 'react-toastify';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <ModalProvider>
                    <div className="container-fluid p-5 m-0 p-md-auto">
                        {children}
                    </div>
                </ModalProvider>
                <ToastContainer
                    position='top-right'
                    autoClose={2500}
                    theme='light'
                    hideProgressBar={true}
                    transition={Zoom}
                />
            </body>
        </html>
    )
}
