
import 'bootstrap/dist/css/bootstrap.min.css';

export const metadata = {
    title: 'Next.js',
    description: 'Generated by Next.js',
}

export default function RootLayout({
    children,
}: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
            <body>
                <div className="container-fluid p-5 m-0 p-md-auto">
                    {children}
                </div>
            </body>
        </html>
    )
}
